baseURL = "https://adilshamji.github.io/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "etch"

[params]
  mainSections = ["posts"]
  paginate = 5
  showDescription = true
  showReadingTime = true
